// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var MaterialUi_Paper = require("@jsiebern/bs-material-ui/src/MaterialUi_Paper.bs.js");

var root = Css.style(/* :: */[
      Css.height(Css.px(100)),
      /* :: */[
        Css.width(Css.pct(90)),
        /* [] */0
      ]
    ]);

var paper = Css.style(/* :: */[
      Css.height(Css.px(80)),
      /* :: */[
        Css.width(Css.pct(100)),
        /* :: */[
          Css.display(/* flex */-1010954439),
          /* :: */[
            Css.justifyContent(/* center */98248149),
            /* :: */[
              Css.alignItems(/* center */98248149),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = {
  root: root,
  paper: paper
};

var component = ReasonReact.statelessComponent("TaskDescription-Wordnet");

function make(description, param) {
  return {
          debugName: component.debugName,
          reactClassInternal: component.reactClassInternal,
          handedOffState: component.handedOffState,
          willReceiveProps: component.willReceiveProps,
          didMount: component.didMount,
          didUpdate: component.didUpdate,
          willUnmount: component.willUnmount,
          willUpdate: component.willUpdate,
          shouldUpdate: component.shouldUpdate,
          render: (function (param) {
              return React.createElement("div", {
                          className: root
                        }, ReasonReact.element(undefined, undefined, MaterialUi_Paper.make(paper, undefined, undefined, undefined, undefined, undefined, [description])));
            }),
          initialState: component.initialState,
          retainedProps: component.retainedProps,
          reducer: component.reducer,
          jsElementWrapped: component.jsElementWrapped
        };
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* root Not a pure module */
