// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$Promise = require("reason-promise/src/js/promise.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_MapInt = require("bs-platform/lib/js/belt_MapInt.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Util$Wordnet = require("../infrastructure/Util.bs.js");
var Graph$Wordnet = require("../infrastructure/Graph.bs.js");
var Domain$Wordnet = require("../domain/Domain.bs.js");
var Wordnet$Wordnet = require("../infrastructure/Wordnet.bs.js");
var MaterialUi_Select = require("@jsiebern/bs-material-ui/src/MaterialUi_Select.bs.js");
var Relations$Wordnet = require("../domain/Relations.bs.js");
var MaterialUi_MenuItem = require("@jsiebern/bs-material-ui/src/MaterialUi_MenuItem.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");
var TaskDescription$Wordnet = require("../components/TaskDescription.bs.js");
var MaterialUi_CircularProgress = require("@jsiebern/bs-material-ui/src/MaterialUi_CircularProgress.bs.js");

var boldText = Css.style(/* :: */[
      Css.fontWeight(/* bold */-1055161979),
      /* [] */0
    ]);

var depthPickerContainer = Css.style(/* :: */[
      Css.height(Css.rem(3)),
      /* :: */[
        Css.width(Css.pct(90)),
        /* :: */[
          Css.display(/* flex */-1010954439),
          /* [] */0
        ]
      ]
    ]);

var depthPicker = Css.style(/* :: */[
      Css.width(Css.rem(5)),
      /* :: */[
        Css.marginRight(Css.rem(0)),
        /* :: */[
          Css.marginLeft(/* auto */-1065951377),
          /* [] */0
        ]
      ]
    ]);

var graphContainer = Css.style(/* :: */[
      Css.height(Css.rem(40)),
      /* :: */[
        Css.width(Css.pct(90)),
        /* :: */[
          Css.display(/* flex */-1010954439),
          /* :: */[
            Css.justifyContent(/* center */98248149),
            /* [] */0
          ]
        ]
      ]
    ]);

var progressContainer = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.alignItems(/* center */98248149),
        /* :: */[
          Css.height(Css.rem(14)),
          /* [] */0
        ]
      ]
    ]);

var Styles = {
  boldText: boldText,
  depthPickerContainer: depthPickerContainer,
  depthPicker: depthPicker,
  graphContainer: graphContainer,
  progressContainer: progressContainer
};

var initialState = {
  relations: /* [] */0,
  synsetMap: Belt_MapInt.empty,
  depth: 1,
  ready: false
};

function loadRelations(depth, send) {
  return $$Promise.Js.get($$Promise.Js.flatMap($$Promise.Js.flatMap($$Promise.Js.flatMap($$Promise.Js.map($$Promise.Js.map(Wordnet$Wordnet.searchSenses("wypadek"), (function (senses) {
                                    return Belt_List.keep(senses, (function (sense) {
                                                  if (sense.lemma === "wypadek") {
                                                    return sense.senseNumber === 1;
                                                  } else {
                                                    return false;
                                                  }
                                                }));
                                  })), Belt_List.headExn), (function (sense) {
                            return Wordnet$Wordnet.synsetForSenseId(sense.id);
                          })), (function (synsetId) {
                        return Relations$Wordnet.path(synsetId, /* Hyponym */0, Caml_option.some(depth), /* () */0);
                      })), (function (relations) {
                    return $$Promise.Js.map($$Promise.Js.map($$Promise.Js.all(Belt_List.map(Domain$Wordnet.distinctSynsets(relations), (function (synsetId) {
                                              return $$Promise.Js.map(Wordnet$Wordnet.sensesForSynset(synsetId), (function (senses) {
                                                            var synset = {
                                                              synsetId: synsetId,
                                                              senses: senses
                                                            };
                                                            return /* tuple */[
                                                                    synsetId,
                                                                    synset
                                                                  ];
                                                          }));
                                            }))), (function (synsets) {
                                      return Belt_MapInt.fromArray(Belt_List.toArray(synsets));
                                    })), (function (synsetMap) {
                                  return /* RelationsLoaded */Block.__(0, [
                                            relations,
                                            synsetMap
                                          ]);
                                }));
                  })), send);
}

var component = ReasonReact.reducerComponent("Three-Wordnet");

function make(param) {
  return {
          debugName: component.debugName,
          reactClassInternal: component.reactClassInternal,
          handedOffState: component.handedOffState,
          willReceiveProps: component.willReceiveProps,
          didMount: (function (self) {
              return loadRelations(self.state.depth, self.send);
            }),
          didUpdate: component.didUpdate,
          willUnmount: component.willUnmount,
          willUpdate: component.willUpdate,
          shouldUpdate: component.shouldUpdate,
          render: (function (self) {
              var description = ReasonReact.element(undefined, undefined, TaskDescription$Wordnet.make(ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, [
                                "Find ",
                                self.state.depth === 1 ? "direct" : "second-order",
                                React.createElement("b", undefined, " hyponyms "),
                                "of \"wypadek(1)\" noun"
                              ])), []));
              var chooseDepth = React.createElement("div", {
                    className: depthPickerContainer
                  }, ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (param, update) {
                              return Curry._1(self.send, /* DepthChanged */Block.__(1, [update.props.value]));
                            }), undefined, undefined, undefined, undefined, undefined, /* `Int */[
                            3654863,
                            self.state.depth
                          ], undefined, undefined, undefined, depthPicker, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, [
                            ReasonReact.element(undefined, undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Int */[
                                      3654863,
                                      1
                                    ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, ["1"])),
                            ReasonReact.element(undefined, undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Int */[
                                      3654863,
                                      2
                                    ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, ["2"]))
                          ])));
              var nodes = Belt_Array.map(Belt_List.toArray(Domain$Wordnet.distinctSynsets(self.state.relations)), (function (synsetId) {
                      return {
                              id: synsetId,
                              label: Util$Wordnet.label(synsetId, self.state.synsetMap),
                              group: undefined
                            };
                    }));
              var edges = Belt_List.toArray(Belt_List.map(self.state.relations, (function (relation) {
                          return {
                                  from: relation.relFrom,
                                  to: relation.relTo,
                                  label: undefined
                                };
                        })));
              var options = {
                nodes: {
                  shape: "dot",
                  size: 10,
                  shadow: true
                },
                edges: {
                  width: 1,
                  length: 100,
                  shadow: true,
                  smooth: {
                    type: "continuous"
                  }
                },
                interaction: {
                  hideEdgesOnDrag: true
                }
              };
              var graph = ReasonReact.element(undefined, undefined, Graph$Wordnet.make(nodes, edges, options, []));
              return React.createElement("div", undefined, description, chooseDepth, React.createElement("div", {
                              className: graphContainer
                            }, self.state.ready ? graph : React.createElement("div", {
                                    className: progressContainer
                                  }, ReasonReact.element(undefined, undefined, MaterialUi_CircularProgress.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, [])))));
            }),
          initialState: (function (param) {
              return initialState;
            }),
          retainedProps: component.retainedProps,
          reducer: (function (action, state) {
              if (action.tag) {
                var depth = action[0];
                return /* UpdateWithSideEffects */Block.__(2, [
                          {
                            relations: state.relations,
                            synsetMap: state.synsetMap,
                            depth: depth,
                            ready: false
                          },
                          (function (self) {
                              return loadRelations(depth, self.send);
                            })
                        ]);
              } else {
                return /* Update */Block.__(0, [{
                            relations: action[0],
                            synsetMap: action[1],
                            depth: state.depth,
                            ready: true
                          }]);
              }
            }),
          jsElementWrapped: component.jsElementWrapped
        };
}

exports.Styles = Styles;
exports.initialState = initialState;
exports.loadRelations = loadRelations;
exports.component = component;
exports.make = make;
/* boldText Not a pure module */
