// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var $$Promise = require("reason-promise/src/js/promise.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_MapInt = require("bs-platform/lib/js/belt_MapInt.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Util$Wordnet = require("../infrastructure/Util.bs.js");
var Graph$Wordnet = require("../infrastructure/Graph.bs.js");
var Domain$Wordnet = require("../domain/Domain.bs.js");
var Wordnet$Wordnet = require("../infrastructure/Wordnet.bs.js");
var Relations$Wordnet = require("../domain/Relations.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");
var TaskDescription$Wordnet = require("../components/TaskDescription.bs.js");
var MaterialUi_CircularProgress = require("@jsiebern/bs-material-ui/src/MaterialUi_CircularProgress.bs.js");

var progressContainer = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.alignItems(/* center */98248149),
        /* :: */[
          Css.height(Css.rem(14)),
          /* [] */0
        ]
      ]
    ]);

var graphContainer = Css.style(/* :: */[
      Css.height(Css.rem(40)),
      /* :: */[
        Css.width(Css.pct(90)),
        /* :: */[
          Css.display(/* flex */-1010954439),
          /* :: */[
            Css.justifyContent(/* center */98248149),
            /* [] */0
          ]
        ]
      ]
    ]);

var Styles = {
  progressContainer: progressContainer,
  graphContainer: graphContainer
};

var initialState = {
  relations: /* [] */0,
  synsetMap: Belt_MapInt.empty,
  ready: false
};

function loadRelations(send) {
  return $$Promise.Js.get($$Promise.Js.flatMap($$Promise.Js.flatMap($$Promise.Js.flatMap(Wordnet$Wordnet.searchSenses("wypadek drogowy"), (function (senses) {
                            return $$Promise.Js.all(Belt_List.map(senses, (function (sense) {
                                              return Wordnet$Wordnet.synsetForSenseId(sense.id);
                                            })));
                          })), (function (synsetIds) {
                        var synsetId = Belt_List.headExn(synsetIds);
                        return Relations$Wordnet.path(synsetId, /* Hypernymy */1, undefined, /* () */0);
                      })), (function (relations) {
                    return $$Promise.Js.map($$Promise.Js.map($$Promise.Js.all(Belt_List.map(Domain$Wordnet.distinctSynsets(relations), (function (synsetId) {
                                              return $$Promise.Js.map(Wordnet$Wordnet.sensesForSynset(synsetId), (function (senses) {
                                                            var synset = {
                                                              synsetId: synsetId,
                                                              senses: senses
                                                            };
                                                            return /* tuple */[
                                                                    synsetId,
                                                                    synset
                                                                  ];
                                                          }));
                                            }))), (function (synsets) {
                                      return Belt_MapInt.fromArray(Belt_List.toArray(synsets));
                                    })), (function (synsetMap) {
                                  return /* RelationsLoaded */[
                                          relations,
                                          synsetMap
                                        ];
                                }));
                  })), send);
}

var component = ReasonReact.reducerComponent("Two-Wordnet");

function make(param) {
  return {
          debugName: component.debugName,
          reactClassInternal: component.reactClassInternal,
          handedOffState: component.handedOffState,
          willReceiveProps: component.willReceiveProps,
          didMount: (function (self) {
              return loadRelations(self.send);
            }),
          didUpdate: component.didUpdate,
          willUnmount: component.willUnmount,
          willUpdate: component.willUpdate,
          shouldUpdate: component.shouldUpdate,
          render: (function (self) {
              var description = ReasonReact.element(undefined, undefined, TaskDescription$Wordnet.make(ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, [
                                "Find closure of",
                                React.createElement("b", undefined, " hypernymy "),
                                "relation for the first meaning of the \"wypadek drogowy\" expression. Create diagram of the relations as a directed graph."
                              ])), []));
              var nodes = Belt_Array.map(Belt_List.toArray(Domain$Wordnet.distinctSynsets(self.state.relations)), (function (synsetId) {
                      return {
                              id: synsetId,
                              label: Util$Wordnet.label(synsetId, self.state.synsetMap),
                              group: undefined
                            };
                    }));
              var edges = Belt_List.toArray(Belt_List.map(self.state.relations, (function (relation) {
                          return {
                                  from: relation.relFrom,
                                  to: relation.relTo,
                                  label: undefined
                                };
                        })));
              var options = {
                nodes: {
                  shape: "dot",
                  size: 10,
                  shadow: true
                },
                edges: {
                  width: 1,
                  length: 100,
                  shadow: true,
                  smooth: {
                    type: "continuous"
                  }
                },
                interaction: {
                  hideEdgesOnDrag: true
                }
              };
              var graph = ReasonReact.element(undefined, undefined, Graph$Wordnet.make(nodes, edges, options, []));
              return React.createElement("div", undefined, description, React.createElement("div", {
                              className: graphContainer
                            }, self.state.ready ? graph : React.createElement("div", {
                                    className: progressContainer
                                  }, ReasonReact.element(undefined, undefined, MaterialUi_CircularProgress.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, [])))));
            }),
          initialState: (function (param) {
              return initialState;
            }),
          retainedProps: component.retainedProps,
          reducer: (function (action, param) {
              return /* Update */Block.__(0, [{
                          relations: action[0],
                          synsetMap: action[1],
                          ready: true
                        }]);
            }),
          jsElementWrapped: component.jsElementWrapped
        };
}

exports.Styles = Styles;
exports.initialState = initialState;
exports.loadRelations = loadRelations;
exports.component = component;
exports.make = make;
/* progressContainer Not a pure module */
