// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_SetInt = require("bs-platform/lib/js/belt_SetInt.js");

function cmp(a, b) {
  return a.id - b.id | 0;
}

var RelationCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

function distinctSynsets(relations) {
  return Belt_SetInt.toList(Belt_SetInt.fromArray(Belt_List.toArray(Belt_List.flatten(Belt_List.map(relations, (function (relation) {
                                return /* :: */[
                                        relation.relFrom,
                                        /* :: */[
                                          relation.relTo,
                                          /* [] */0
                                        ]
                                      ];
                              }))))));
}

exports.RelationCmp = RelationCmp;
exports.distinctSynsets = distinctSynsets;
/* RelationCmp Not a pure module */
