// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactGraphVis = require("react-graph-vis");

function make(nodes, edges, options, children) {
  var props = {
    graph: {
      nodes: nodes,
      edges: edges,
      options: options
    }
  };
  return ReasonReact.wrapJsForReason(ReactGraphVis.default, props, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
