// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


function calculate(shortestPath, $staropt$star, param) {
  var depth = $staropt$star !== undefined ? $staropt$star : 11;
  if (shortestPath === 0) {
    return 0;
  } else {
    return -Math.log(shortestPath / (2 * depth));
  }
}

exports.calculate = calculate;
/* No side effect */
