// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_MapInt = require("bs-platform/lib/js/belt_MapInt.js");

function label(synsetId, synsetMap) {
  var match = Belt_MapInt.get(synsetMap, synsetId);
  if (match !== undefined) {
    return Belt_List.reduce(match.senses, "", (function (acc, sense) {
                  if (acc === "") {
                    return sense.lemma;
                  } else {
                    return acc + ("\n" + sense.lemma);
                  }
                }));
  } else {
    return String(synsetId);
  }
}

exports.label = label;
/* No side effect */
