version: "3.2"
services:
  elasticsearch:
    image: elastic-morfologik:0.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: "./elk/elastic"
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      - SERVER_NAME="Kibana"
      - SERVER_NAME=http://elasticsearch:9200
    volumes:
      - type: bind
        source: "./elk/kibana"
        target: /usr/share/kibana/data
    ports:
      - "5601:5601"
