// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var One$Wordnet = require("./views/One.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Two$Wordnet = require("./views/Two.bs.js");
var Five$Wordnet = require("./views/Five.bs.js");
var Four$Wordnet = require("./views/Four.bs.js");
var Three$Wordnet = require("./views/Three.bs.js");
var Layout$Wordnet = require("./Layout.bs.js");
var Router$Wordnet = require("./Router.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

var container = Css.style(/* :: */[
      Css.height(Css.pct(100)),
      /* [] */0
    ]);

var Styles = /* module */[/* container */container];

var initialState = /* record */[/* route : One */0];

var component = ReasonReact.reducerComponent("Application-Wordnet");

function routeToComponent(route) {
  switch (route) {
    case 0 : 
        return ReasonReact.element("1", undefined, One$Wordnet.make(/* array */[]));
    case 1 : 
        return ReasonReact.element("2", undefined, Two$Wordnet.make(/* array */[]));
    case 2 : 
        return ReasonReact.element("3", undefined, Three$Wordnet.make(/* array */[]));
    case 3 : 
        return ReasonReact.element("4", undefined, Four$Wordnet.make(/* array */[]));
    case 4 : 
        return ReasonReact.element("5", undefined, Five$Wordnet.make(/* array */[]));
    
  }
}

function make(param) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherId = ReasonReactRouter.watchUrl((function (url) {
                      return Curry._1(self[/* send */3], /* UpdateRoute */[Router$Wordnet.mapUrlToRoute(url)]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            return ReasonReactRouter.unwatchUrl(watcherId);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: container
                        }, ReasonReact.element(undefined, undefined, Layout$Wordnet.make(/* array */[routeToComponent(self[/* state */1][/* route */0])])));
            }),
          /* initialState */(function (param) {
              return initialState;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, param) {
              return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.initialState = initialState;
exports.component = component;
exports.routeToComponent = routeToComponent;
exports.make = make;
/* container Not a pure module */
