// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var One$Wordnet = require("./One.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Layout$Wordnet = require("./Layout.bs.js");

var container = Css.style(/* :: */[
      Css.height(Css.pct(100)),
      /* [] */0
    ]);

var Styles = /* module */[/* container */container];

var component = ReasonReact.statelessComponent("Application-Wordnet");

function make(param) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return React.createElement("div", {
                          className: container
                        }, ReasonReact.element(undefined, undefined, Layout$Wordnet.make(/* array */[ReasonReact.element(undefined, undefined, One$Wordnet.make(/* array */[]))])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* container Not a pure module */
