// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Application$Wordnet = require("./Application.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Application$Wordnet.make(/* array */[])), "root");

/*  Not a pure module */
