// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


var Typography = 0;

var Paper = 0;

var Table = 0;

var TableHead = 0;

var TableBody = 0;

var TableRow = 0;

var TableCell = 0;

exports.Typography = Typography;
exports.Paper = Paper;
exports.Table = Table;
exports.TableHead = TableHead;
exports.TableBody = TableBody;
exports.TableRow = TableRow;
exports.TableCell = TableCell;
/* No side effect */
