// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "five" : 
          if (match[1]) {
            return /* One */0;
          } else {
            return /* Five */4;
          }
      case "four" : 
          if (match[1]) {
            return /* One */0;
          } else {
            return /* Four */3;
          }
      case "one" : 
          return /* One */0;
      case "three" : 
          if (match[1]) {
            return /* One */0;
          } else {
            return /* Three */2;
          }
      case "two" : 
          if (match[1]) {
            return /* One */0;
          } else {
            return /* Two */1;
          }
      default:
        return /* One */0;
    }
  } else {
    return /* One */0;
  }
}

function mapRouteToUrl(route) {
  switch (route) {
    case 0 : 
        return "/one";
    case 1 : 
        return "/two";
    case 2 : 
        return "/three";
    case 3 : 
        return "/four";
    case 4 : 
        return "/five";
    
  }
}

function navigate(route) {
  return ReasonReactRouter.push(mapRouteToUrl(route));
}

function getInitialRoute(param) {
  var route = mapUrlToRoute(ReasonReactRouter.dangerouslyGetInitialUrl(/* () */0));
  ReasonReactRouter.push(mapRouteToUrl(route));
  return route;
}

exports.mapUrlToRoute = mapUrlToRoute;
exports.mapRouteToUrl = mapRouteToUrl;
exports.navigate = navigate;
exports.getInitialRoute = getInitialRoute;
/* ReasonReactRouter Not a pure module */
